name: nekoflixx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.9
  get_storage: ^2.1.1
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  animated_splash_screen: ^1.3.0
  video_player: ^2.8.3
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogoUpscaled.webp"